#-------------------------------
# General Site Settings

menu:
- {name: 'Projects', url: ''}
# - {name: 'Blog', url: 'pages/blog.html'}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal portfolio powered by Jekyll and GitHub Pages '
  rel-author: 'https://plus.google.com/u/0/#'
  rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: 'UA-112060364-3'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # Projects portfolio

  This website is a portfolio containing a series of Head-Mounted Augmented Reality sound artworks/projects from the Australian National University. You can checkout [our latest work](projects/proj-1.html) to be appeared at [NIME2021](http://nime2021.org/).
  More to come :)

contact: >
  # Contact
  You may contact me [through my email](mailto:yichen.wang@anu.edu.au) (who is running the website) if you have any questions or directly contact other people heightened by their name.

#-------------------------------
# Work Section

projects:
- {name: 'Sonic Sculptural Staircase in Head Mounted Augmented Reality', folder: 'proj-1', file: 'projects/proj-1.html'}
# - {name: 'Sonic Sculpture', folder: 'proj-2', file: 'projects/proj-2.html'}
# - {name: 'Project Three', folder: 'proj-3', file: 'projects/proj-3.html'}
# - {name: 'Project Four', folder: 'proj-4', file: 'projects/proj-4.html'}
# - {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section

social:
# - {icon: 'twitter', link: '#'}
# - {icon: 'instagram', link: '#'}
# - {icon: 'github', link: '#'}
# - {icon: 'linkedin', link: '#'}
- {icon: 'envelope', link: 'mailto:yichen.wang@anu.edu.au'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
